channels:
- conda-forge
dependencies:
- python=3.8.10
- pip<=24.3.1
- pip:
  - mlflow==2.17.2
  - argparse==1.4.0
  - cloudpickle==2.2.1
  - numpy==1.24.3
  - psutil==5.9.5
  - scikit-learn==1.1.1
  - scipy==1.10.1
name: mlflow-env
